### ISSUE TITLE
请教修改config.yaml 支持旧参数V2Ray ws path

### ISSUE THREAD

**Issue by ps4jpacce** [phlinhng/v2ray-tcp-tls-web#44]
你好，请教一下，旧vps V2Ray 为ws tls模式，path为vtest，

原版caddy参数为

```
mytest213.pw {
    gzip
timeouts none
    proxy / https://www.pcgeek.com.au {
        except /vtest
    }
    proxy /game 127.0.0.1:27292 {
        without /vtest
        websocket
    }
}
import sites/*

```

旧节点10几人在用，
现在想用您一键脚本，开台新的VPS无缝过渡，
请教下面/etc/tls-shunt-proxy/config.yaml应该如何改，
大概V2Ray我都懂些，指点一下我会明白 :)

```
listen: 0.0.0.0:443
redirecthttps: 0.0.0.0:80

vhosts:
  - name: mytest213.pw
    tlsoffloading: true
    managedcert: true
    keytype: p256
    alpn: h2,http/1.1
    protocols: tls12,tls13
    http:
      ##CDN@paths:
        ##CDN@- path: /FAKECDNPATH
        ##CDN@  handler: proxyPass
        ##CDN@  args: 127.0.0.1:3566
      handler: fileServer
      args: /var/www/html
    default:
      handler: proxyPass
      args: unix:/tmp/v2ray-ds/v2ray.sock
```
